repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
      args: [ --assume-in-merge ]
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
